name: 'macumbei'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./media:/app/media
    ports:
      - "80:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_IP=${SERVER_IP}
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: macumbei-app
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=macumbei_db
      - POSTGRES_USER=macumbei_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: macumbei-db
    restart: unless_stopped

volumes:
  postgres_data:
