# Generated by Django 4.2.24 on 2025-09-28 23:54

from django.db import migrations, models
import pontos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.PositiveSmallIntegerField(choices=[(1, 'Defumação'), (2, 'Limpeza'), (3, 'Corte'), (4, 'Descarrego'), (5, 'N/A')], default=5)),
                ('linha', models.PositiveSmallIntegerField(choices=[(1, 'Astro'), (2, 'Preto velho'), (3, 'Ogum'), (4, 'Caboclo de pena'), (5, 'Mestres'), (6, 'Exu'), (7, 'Erê'), (8, 'N/A')], default=8)),
                ('entidade', models.CharField(blank=True, max_length=20, null=True)),
                ('letra', models.TextField(max_length=777)),
                ('link_audio', models.FileField(upload_to=pontos.models.audio_path)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
